const transactions = [
	{
		accountNumber: 84793357388,
		description: 'Microsoft OneDrive',
		type: 'Virtual Card',
		cleared: true,
		amount: 1.99,
		merchantName: 'Microsoft',
		category: 'Shopping & Entertainment: Online Services',
	},
	{
		accountNumber: 84793357388,
		description: 'YouTube Premium',
		type: 'Debit Card',
		cleared: true,
		amount: 11.99,
		merchantName: 'Google',
		category: 'Shopping & Entertainment: Entertainment',
	},
	{
		accountNumber: 84793357388,
		description: 'Microsoft OneDrive',
		type: 'Virtual Card',
		cleared: true,
		amount: 1.99,
		merchantName: 'Microsoft',
		category: 'Shopping & Entertainment: Online Services',
	},
	{
		accountNumber: 84793357388,
		description: 'Paris Baguette Purchase',
		type: 'Debit Card',
		cleared: true,
		amount: 59.99,
		merchantName: 'Paris Baguette',
		category: 'Eating Places and Restaurants',
	},
	{
		accountNumber: 84793357388,
		description: 'ATM Withdrawal',
		type: 'Withdrawal',
		cleared: true,
		amount: 200,
		merchantName: 'Random ATM',
		category: 'Cash, Checks & Misc: ATM/Cash Withdrawals',
	},
	{
		accountNumber: 84793357388,
		description: 'Amazon: Direct Deposit',
		type: 'Deposit',
		cleared: true,
		amount: 100500.69,
		merchantName: 'Jeff Bezos',
		category: 'Income: Paychecks/Salary',
	},
	{
		accountNumber: 42992483991,
		description: 'T-Mobile Autopay',
		type: 'Visa',
		cleared: true,
		amount: 159.99,
		merchantName: 'T-Mobile',
		category: 'Home & Utilities: Telephone Services',
	},
	{
		accountNumber: 42992483991,
		description: 'Costco Wholesale',
		type: 'Visa',
		cleared: true,
		amount: 168.31,
		merchantName: 'Costco',
		category: 'Shopping & Entertainment: General Merchandise',
	},
	{
		accountNumber: 42992483991,
		description: 'Microsoft OneDrive',
		type: 'Virtual Card',
		cleared: true,
		amount: 1.99,
		merchantName: 'Microsoft',
		category: 'Shopping & Entertainment: Online Services',
	},
	{
		accountNumber: 42992483991,
		description: 'Netflix Autopay',
		type: 'Debit Card',
		cleared: true,
		amount: 10.99,
		merchantName: 'Netflix',
		category: 'Shopping & Entertainment: Online Services',
	},
	{
		accountNumber: 42992483991,
		description: 'ATM Withdrawal',
		type: 'Withdrawal',
		cleared: true,
		amount: 200,
		merchantName: 'Random ATM',
		category: 'Cash, Checks & Misc: ATM/Cash Withdrawals',
	},
	{
		accountNumber: 42992483991,
		description: 'Tesla: Direct Deposit',
		type: 'Deposit',
		cleared: true,
		amount: 420.69,
		merchantName: 'Elon Musk',
		category: 'Income: Paychecks/Salary',
	},
];

module.exports = transactions;
